KV async job mgr
iqiyi/auklet pull request #1
Opened 2018-06-22 08:29 UTC by bluesalt

This PR implements a new async pending job management design which persists the jobs into RocksDB to reduce space usage and improve performance.

2018-06-22 08:31 UTC, bluesalt commented
@peteryj

2018-06-22 09:05 UTC, abitduck commented on cmd/auklet/command/dump_db.go
> +		} else {
keyType可以指定一下，改为bool型也行，可降低用户使用门槛

2018-06-22 09:23 UTC, abitduck commented on common/fs/mount_monitor.go
> +package fs
这个文件没有Copyright信息，也没看到引用

2018-06-23 05:18 UTC, abitduck requested changes
Great feature comes ~ some code need have a tweak

2018-06-23 05:18 UTC, abitduck commented on common/fs/utils.go
> +func TempDir(driveRoot, device string, policy int) string {
var policy is unused, should have a comment if needed

2018-06-23 05:18 UTC, abitduck commented on objectserver/errors.go
> +	ErrHashConfNotFound     = errors.New("unable to read hash prefix and suffxi")
spell error: `suffxi` to `suffix`

2018-06-23 05:18 UTC, abitduck commented on objectserver/fs_async_job_mgr.go
> +			if err != nil {
if read file fail too many times, should raise exception, disk error or file permission may cause this problem; always continue is not a good idea~

2018-06-23 05:18 UTC, abitduck commented on cmd/auklet/command/dump_db.go
> +		} else {
should give  keyType for KVAsync a name, and should update the command usage

2018-06-23 05:18 UTC, abitduck commented on common/fs/mount_monitor.go
> +package fs
This file do not have copyright info and code is unused

2018-06-25 09:14 UTC, bluesalt commented on common/fs/utils.go
> +func TempDir(driveRoot, device string, policy int) string {
It is a bug. Will fix it.

2018-06-25 09:18 UTC, bluesalt commented on objectserver/fs_async_job_mgr.go
> +			if err != nil {
That is why bloom filter is used.

2018-06-25 09:43 UTC, abitduck approved these changes

2018-06-25 09:50 UTC, merged